### ISSUE TITLE
Gives incorrect number of driver nodes

### ISSUE THREAD

**Issue by 97amarnathk** [ntamas/netctrl#5]
Hey. I am working on a similar project. I built your code and ran it on the following graph:

**graph.txt**

```
0 1
0 2
0 3
```

`./netctrl graph.txt`

Now it outputs only the node 0 to be a driver node. But actually 0, 1, 2 are the driver nodes if we refer to Liu's paper.

**Comment by ntamas** [comment]
Please add `-m liu` to the command line options. `netctrl` uses the switchboard model of Nepusz & Vicsek by default, not the Liu model.
